// react-app/src/App.js
import React, { Component } from 'react';
import './App.css';




class App extends Component {

  // state data
  data = {
    msg: ' Hello React  <a href="#" class="badge badge-dark" onclick=alert(1)>clickme</a> ',
    rawjs: 'alert(1)',
    url: 'javascript:alert(1)',
    evt: 'alert(1)',
    raw: '{msg}',
    sample: 'sample',
    sample1: 'sample',
    sample2: 'sample',
  }

  hover = () => {
    console.log('trigged');
    // return this.data.msg
  }

  render() {
    return (

      <div className = "container-fluid" >
        <br />

        <div className = "card" >
          <h5 className = "card-header" > HTML and Javascript Injection </h5>
          <div className = "card-body" >

            <div>
              <h6 class="card-subtitle mb-2 text-muted">Default Render</h6>
              <span className = "badge badge-primary" > {this.data.raw} 
              </span> -> <span className="badge badge-success"> Safe </span>

              <div>
              {this.data.msg}
              </div>
            </div>
            <hr />

            <div>
              <h6 class="card-subtitle mb-2 text-muted">dangerous Render</h6>
              <span className = "badge badge-primary" > {
                "<div dangerouslySetInnerHTML = {{__html: this.data.msg }}"
              } </span> -> <span className="badge badge-danger"> UnSafe </span>

              <div dangerouslySetInnerHTML = {{__html: this.data.msg}} />

            </div>
          </div>
        </div>

        <br />

        <div className="card" >
          <h5 className="card-header" > Attribute and Event Injection </h5>
          <div className="card-body" >

            <div>
              <h6 class="card-subtitle mb-2 text-muted">Attribute Default Render</h6>
              <span className="badge badge-primary" > {this.data.url}
              </span> -> <span className="badge badge-danger"> Unsafe </span>

              <div>
                <a className="badge badge-dark"  href={this.data.url}>clickme</a>
                
              </div>
            </div>
            <hr />

            <div>
              <h6 class="card-subtitle mb-2 text-muted">Event Default Render</h6>
              <span className="badge badge-primary" > 
              {"onmouseover=" + this.data.evt } </span> -> <span className="badge badge-success"> Safe </span>

              <div>
              <a className="badge badge-secondary" onClick="console.log(1)" onMouseOver={this.data.evt}> hoverme </a>
              </div>
            </div>
          </div>
        </div>


      </div>
    );
  }
}

export default App;

// angular-app/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})
export class AppComponent  {
    name = 'Angular 7';
    title = 'angular-app';


    // This should cause an error
    // alert(3);

    eviltag = '<a href="javascript:alert(1)" class="badge badge-dark" onclick=alert(1)>clickme</a><script>console.log("XSS")</script>';
    msg = ' Hello Angular  <a href="javascript:alert(1)" class="badge badge-dark" onclick=alert(1)>clickme</a> ';

    rawjs = 'alert(1)';
    url = 'javascript:alert(1)';
    evt = 'alert(1)';
    raw = '{{msg}}';

    onClick(){
    console.log('clicked!');
    }

}


<div class="container-fluid" >
<br />

<div class="card" >
  <h5 class="card-header"> HTML and Javascript Injection </h5>
  <div class="card-body">

    <div>
    <h6 class="card-subtitle mb-2 text-muted">Default Render</h6>  
      <span class="badge badge-primary" > {{raw}}
      </span> -> <span class="badge badge-success"> Safe </span>

      <div>
        {{msg}}
      </div>
    </div>

    <hr />

    <div>
        <h6 class="card-subtitle mb-2 text-muted">Default innerHTML Render</h6>  
      <span class="badge badge-primary" >  [innerHTML]="msg"
      </span> -> <span class="badge badge-success"> Safe </span>

      <div [innerHTML]="msg"></div>

    </div>

    <hr>
    <div>
        <h6 class="card-subtitle mb-2 text-muted">Unsafe innerHTML Render</h6>  
      <span class="badge badge-primary" >  [innerHTML]="msg | sanitizeHtml"
      </span> -> <span class="badge badge-danger"> Unsafe </span>

      <div>
        <span [innerHTML]="msg | sanitizeHtml"></span>
    </div>

    </div>



  </div>

</div>

<br />

<div class="card" >
<h6 class="card-subtitle mb-2 text-muted">Default Attribute Render</h6>  

  <h5 class="card-header"> Attribute and Event Injection </h5>
  <div class="card-body">

    <div>
      <span class="badge badge-primary" > href={{url}}
      </span> -> <span class="badge badge-success"> Safe </span>

      <div>
        <a class="badge badge-secondary" href={{url}}>clickme</a>
      </div>
    </div>

    <hr>

    <div>
<h6 class="card-subtitle mb-2 text-muted">Default Event Render</h6>  

      <span class="badge badge-primary" > onclick={{evt}}
      </span> -> <span class="badge badge-success"> Safe </span>

      <div>
        <a class="badge badge-secondary" href="#" (click)="onClick()">clickme</a>
      </div>
  </div>

</div>




</div>
